* BBIMs

Thesis research project into the carbon-removal potential of bio-based
insulation materials (BBIMs)

* Demo

housing scenarios
#+begin_src python
houses_per_year_slow(150000, 27)
houses_per_year_fast(150000, 27)
#+end_src

Large differences between cork / cellulose / stone wool
#+begin_src python
dataset = make_datasets()
dataset['cork']
dataset['stone wool']
dataset['cellulose']
#+end_src

Plotting them:
#+begin_src python
plot_GWI(['cork', 'cellulose', 'stone wool'], building_scenario='normal', plottype='inst')
plot_GWI(['cork', 'cellulose', 'stone wool'], building_scenario='normal', plottype='cum')
#+end_src

* DLCA

[[file:DLCA.py]]

Notes
- make_dataset assumes positive CO2bio, DLCA assumes negative
- Where did I get the alpha values? They are different from Hoxha e.a. 2020

** Missing data

- EcoInvent: Flax, Hemp, Straw, EPS
- Biogenic CO2: Hemp

** Anomalies

#+begin_src python
df = pd.read_csv("data/Ecoinvent.tsv", sep="\t")
sum(df['kg CO2-eq']<df['kg CO2'])
#+end_src

890 / 5421 rows have higher CO2 than CO2-eq

** TODO

- Write to output file
- Generate better plots (radiative forcing, GWP)
- Decide how to handle tf of interest and time_horizon for construction (i.e.
  consider the impact until 2100 of houses constructed until 2050)
- Check all GHGs are properly taken into account (e.g. CO turns into CO2)
- Gather crop rotation periods

* Make Dataset

[[file:make_dataset.py]]

Notes
- CO2_bio:
  - Currently not counting biogenic CO2 in cellulose as it is recycled
  - Missing hemp
- Add KG of insulation per house depending on material
  - currently using placeholder value of 1000kg per unit
- Check if dataset is correctly read in with dots/commas
- check lifecycle stages which are included now
  - a1-a3 from Ecoinvent.tsv
  - C from carbon content (KBOB)
    - how does this work for non-biobased?
  - D: can make some assumptions

**  CO2 issues

*** Prepend 0s to extend emissions

#+begin_src python
# Do I want to prepend 0 rows for the lifetime of the building? Maybe only if they are plant based materials...
dataset = pd.DataFrame(
    np.zeros((MATERIALS[material]["lifetime"], 4)), columns=dataset.columns
).append(dataset, ignore_index=True)
#+end_src

*** CO2bio
It seems the EcoInvent data for BBIMs (CO2) is quite high. I thought biogenic
CO2 might be included? I expect not, as it should just be phase A1-A3 but in
case it needs to be subtracted in make_dataset:

#+begin_src python
# subtract biogenic co2 from kg co2
biogenic = [
    insulation_per_year[i] * MATERIALS[material]["CO2bio"]
    if i < years
    else 0.0
    for i in range(len(insulation_per_year))
]
dataset["kg CO2"] = dataset["kg CO2"] + biogenic
dataset["kg CO2"] = (
    dataset["kg CO2"]
    + np.append(np.zeros(MATERIALS[material]["lifetime"]), biogenic)[
        :timeframe
    ]
)
#+end_src

** TODO

- Add KG of insulation per house depending on material
- Fix placeholder values for rotation time - (model N(r/2, r/4) ?)
  - check if loop i in range(rotation) works for species with r=0.5
- Remove placeholder values
  - M2 Facades, Rvalue, lambda values
