* BBIMs

Thesis research project into the carbon-removal potential of bio-based
insulation materials (BBIMs)

* DLCA

[[file:DLCA.py]]

Notes
- make_dataset assumes positive CO2bio, DLCA assumes negative

** Rotation

      #+begin_src python
def CO2bio(material, ipy, lifetime, timeframe):
    CO2bio_per_year = np.zeros(len(ipy) + MATERIALS[material]["rotation"])
    for i, kg in enumerate(ipy):
        for j in range(MATERIALS[material]["rotation"]):
            CO2bio_per_year[i + j] += (
                kg
                * MATERIALS[material]["CO2bio"]
                / MATERIALS[material]["rotation"]
            )
    return CO2bio_per_year[:timeframe]
#+end_src

** Issue: Straw GWI_inst negative trail

*** Culprit

The definition of the atmospheric decay function from Hoxha e.a. (2020) is as
below. For large t, this function goes to a0Bern, which means that for large
timeframes, the original negative emissions in the straw case still contribute
20% - which is probably far from the true behaviour.

Need to find a better approximation of the atmospheric CO2 curve somewhere.

#+begin_src python
def C_CO2(t):
    return (
        a0Bern
        + aBern[0] * np.exp(-t / TauCO2[0])
        + aBern[1] * np.exp(-t / TauCO2[1])
        + aBern[2] * np.exp(-t / TauCO2[2])
    )
a0Bern = 0.217
aBern = [0.259, 0.338, 0.186]
TauCO2 = [172.9, 18.51, 1.186]

def exp3(tf=100):
    x = np.arange(tf)
    y1 = [C_CO2(i) for i in range(tf)]
    y2 = [C_CH4(i) for i in range(tf)]
    y3 = [C_N2O(i) for i in range(tf)]
    plt.plot(x, y1, label="CO2")
    plt.plot(x, y2, label="CH4")
    plt.plot(x, y3, label="N2O")
    plt.legend()
    plt.show()
    plt.close()
#+end_src

*** Explanation

From what I have explored so far the model seems correct. My explanation is as
follows:
The GWI(t) in year t is the sum over all years j=0 to j=t. For each of these
years we count the emissions up to that year and multiply them with the
necessary reduction factor (emissions from longer ago have a smaller
influence).
In the case of straw here, there is a huge negative set of emissions at the
start which results in these negative emissions being summed over for all the
rest of the years in GWI

*** exploration
For straw, the trail of GWI_inst drops down from a small positive peak back to
negative. In it's limit it should go to 0. Let's explore what's going on.

Experiments to plot:
  #+begin_src python
def exp(
    materials=["straw"],
    building_scenario="normal",
    total_houses=150000,
    time_horizon=2050,
    timeframe=200,
    plottype="inst",
    outfile=False,
):
    GWIs = DLCA(
        materials, building_scenario, total_houses, time_horizon, timeframe
    )
    x = np.arange(timeframe) + 2023
    for material in materials:
        for ghg in GWIs["straw"][plottype]:
            plt.plot(x, GWIs[material][plottype][ghg], label=ghg)
    plt.xlabel("Years")
    plt.ylabel("Radiative forcing " + plottype)
    plt.legend()
    plt.title(f"Global warming Impact ({plottype}, {building_scenario})")
    plt.grid(True)

    plt.show()

    plt.close()


def exp2(timeframe=10):
    tmp = pd.DataFrame(
        np.zeros((timeframe, 4)), columns=["CO2", "CH4", "N2O", "CO"]
    )
    tmp.loc[0] = [1e6, 1e4, 2e3, 1e4]
    GWI_inst = GWI(tmp, timeframe)
    GWI_inst_tot = GWI_inst.sum(axis=1)
    GWI_cum = GWI_inst_tot.cumsum()
    x = np.arange(timeframe) + 2023
    for ghg in GWI_inst:
        plt.plot(x, GWI_inst[ghg], label=ghg)
    plt.legend()
    plt.show()
    plt.close()
#+end_src

  #+begin_src python
[C_CO2(i) for i in range(200)]
[C_CH4(i) for i in range(200)]
[C_N2O(i) for i in range(200)]
#+end_src

All of these seem sensible and correct.
Small part of a df showing the CO2 emissions and the GWI_inst shows the
problem:

| index |           CO2 |        CH4 |        N2O |         CO |          inst |
|-------+---------------+------------+------------+------------+---------------|
|     0 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.804726e-09 |
|     1 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -3.423677e-09 |
|     2 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -4.943615e-09 |
|     3 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -6.402801e-09 |
|     4 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -7.818577e-09 |
|     5 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -9.199240e-09 |
|     6 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.054915e-08 |
|     7 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.187094e-08 |
|     8 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.316644e-08 |
|     9 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.443714e-08 |
|    10 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.568429e-08 |
|    11 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.690908e-08 |
|    12 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.811256e-08 |
|    13 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -1.929576e-08 |
|    14 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.045962e-08 |
|    15 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.160507e-08 |
|    16 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.273296e-08 |
|    17 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.384410e-08 |
|    18 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.493927e-08 |
|    19 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.601920e-08 |
|    20 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.708460e-08 |
|    21 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.813613e-08 |
|    22 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -2.917441e-08 |
|    23 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -3.020003e-08 |
|    24 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -3.121358e-08 |
|    25 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -3.221558e-08 |
|    26 | -1.184444e+06 | 160.844444 | 292.257778 | 384.421644 | -3.320654e-08 |
|    27 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.238223e-08 |
|    28 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.173359e-08 |
|    29 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.117432e-08 |
|    30 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.066655e-08 |
|    31 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.019335e-08 |
|    32 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.974678e-08 |
|    33 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.932284e-08 |
|    34 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.891925e-08 |
|    .. |            .. |         .. |         .. |         .. |            .. |
|   100 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  5.505687e-09 |
|   101 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  6.365927e-09 |
|   102 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  5.406442e-09 |
|   103 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  4.602033e-09 |
|   104 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  3.890165e-09 |
|   105 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  3.242107e-09 |
|   106 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  2.643812e-09 |
|   107 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  2.087670e-09 |
|   108 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  1.568959e-09 |
|   109 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  1.084302e-09 |
|   110 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  6.310007e-10 |
|   111 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 |  2.067378e-10 |
|   112 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -1.905564e-10 |
|   113 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.627677e-10 |
|   114 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -9.116313e-10 |
|   115 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -1.238751e-09 |
|   116 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -1.545615e-09 |
|   117 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -1.833600e-09 |
|   118 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.103988e-09 |
|   119 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.357967e-09 |
|   120 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.596643e-09 |
|   121 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -2.821040e-09 |
|   122 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.032114e-09 |
|   123 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.230751e-09 |
|   124 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.417776e-09 |
|   125 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.593955e-09 |
|   126 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.760001e-09 |
|   127 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -3.916580e-09 |
|   128 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.064307e-09 |
|   129 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.203759e-09 |
|   130 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.335469e-09 |
|   131 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.459937e-09 |
|   132 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.577627e-09 |
|   133 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.688972e-09 |
|   134 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.794373e-09 |
|   135 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.894208e-09 |
|   136 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -4.988826e-09 |
|   137 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.078554e-09 |
|   138 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.163696e-09 |
|   139 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.244536e-09 |
|   140 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.321341e-09 |
|   141 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.394356e-09 |
|   142 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.463814e-09 |
|   143 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.529929e-09 |
|   144 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.592905e-09 |
|   145 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.652928e-09 |
|   146 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.710175e-09 |
|   147 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.764810e-09 |
|   148 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.816987e-09 |
|   149 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.866850e-09 |
|   150 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.914534e-09 |
|   151 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -5.960164e-09 |
|   152 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.003858e-09 |
|   153 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.045727e-09 |
|   154 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.085874e-09 |
|   155 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.124395e-09 |
|   156 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.161381e-09 |
|   157 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.196918e-09 |
|   158 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.231085e-09 |
|   159 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.263955e-09 |
|   160 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.295601e-09 |
|   161 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.326087e-09 |
|   162 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.355474e-09 |
|   163 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.383821e-09 |
|   164 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.411183e-09 |
|   165 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.437610e-09 |
|   166 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.463149e-09 |
|   167 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.487847e-09 |
|   168 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.511746e-09 |
|   169 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.534884e-09 |
|   170 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.557301e-09 |
|   171 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.579031e-09 |
|   172 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.600106e-09 |
|   173 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.620560e-09 |
|   174 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.640420e-09 |
|   175 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.659715e-09 |
|   176 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.678470e-09 |
|   177 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.696710e-09 |
|   178 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.714459e-09 |
|   179 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.731738e-09 |
|   180 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.748568e-09 |
|   181 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.764969e-09 |
|   182 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.780958e-09 |
|   183 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.796553e-09 |
|   184 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.811771e-09 |
|   185 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.826626e-09 |
|   186 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.841135e-09 |
|   187 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.855309e-09 |
|   188 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.869164e-09 |
|   189 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.882710e-09 |
|   190 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.895960e-09 |
|   191 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.908924e-09 |
|   192 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.921614e-09 |
|   193 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.934039e-09 |
|   194 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.946209e-09 |
|   195 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.958133e-09 |
|   196 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.969819e-09 |
|   197 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.981275e-09 |
|   198 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -6.992509e-09 |
|   199 |  0.000000e+00 |   0.000000 |   0.000000 |   0.000000 | -7.003529e-09 |

Even though there are no more emissions (negative nor positive), the radiative
forcing is going down to below zero - as if there were negative emissions.

Next step is to check if DCF works properly
  #+begin_src python
DCF(200)
#+end_src

** TODO

- Write to output file
- Generate better plots (radiative forcing, GWP)
- Could explore separately plotting different GHGs

* Make Dataset

[[file:make_dataset.py]]

** Plots

# Houses per year

#+begin_src python
def hpy(houses=150000, years=27, plottype="inst", outfile=False):
    if plottype == "inst":
        slow = houses_per_year_slow(houses, years)
        fast = houses_per_year_fast(houses, years)
        normal = [houses / years for i in range(years)]
        title = "Number of houses constructed per year"
        x = np.arange(years) + 2023
    else:
        slow = [(houses / (years ** 2)) * x ** 2 for x in range(years + 1)]
        fast = [(houses / (years ** 0.5)) * x ** 0.5 for x in range(years + 1)]
        normal = [i * houses / years for i in range(years + 1)]
        title = "Total number of houses constructed"
        x = np.arange(years + 1) + 2023
    plt.plot(x, slow, label="slow")
    plt.plot(x, fast, label="fast")
    plt.plot(x, normal, label="normal")
    plt.legend()
    plt.title(title)
    plt.grid(True)

    if outfile:
        plt.savefig(f"plots/houses_per_year.svg")
    else:
        plt.show()
    plt.close()

#+end_src


** B/C/D

*** End-of-life

- Need to add EoL data from ecoinvent_waste.csv (module C)
- Optional module D benefits from ecoinvent_energy.csv (assuming energy
  recovery / biogas production)

Relevant EcoInvent data
  #+begin_src python
MATERIALS = {
    "cellulose": {  # Ecoinvent
        "name": "Cellulose fibre, inclusive blowing in {CH}| production | Cut-off, S",
        "lambda": 0.038,
        "density": 52,
        "CO2bio": -0,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Biowaste {CH}| treatment of biowaste, industrial composting | Cut-off, S",
            "Biowaste {CH}| treatment of biowaste by anaerobic digestion | Cut-off, S",
            "Biowaste {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
        ],
    },
    "cork": {  # Ecoinvent
        "name": "Cork slab {RER}| production | Cut-off, S",
        "lambda": 0.04,  # placeholder
        "density": 100,  # placeholder
        "CO2bio": -0.496,
        "rotation": 11,
        "lifetime": 50,
        "waste": [
            "Biowaste {CH}| treatment of biowaste, industrial composting | Cut-off, S",
            "Biowaste {CH}| treatment of biowaste by anaerobic digestion | Cut-off, S",
            "Biowaste {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
        ],
    },
    "flax": {
        "name": "",
        "lambda": 0.04,  # placeholder
        "density": 40,
        "CO2bio": -0.44,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Biowaste {CH}| treatment of biowaste, industrial composting | Cut-off, S",
            "Biowaste {CH}| treatment of biowaste by anaerobic digestion | Cut-off, S",
            "Biowaste {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
        ],
    },
    "hemp": {
        "name": "",
        "lambda": 0.041,
        "density": 36,
        "CO2bio": -0.44,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Biowaste {CH}| treatment of biowaste, industrial composting | Cut-off, S",
            "Biowaste {CH}| treatment of biowaste by anaerobic digestion | Cut-off, S",
            "Biowaste {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
        ],
    },
    "straw": {  # Ecoinvent
        "name": "Straw {CH}| wheat production, Swiss integrated production, extensive | Cut-off, S",
        "lambda": 0.44,
        "density": 100,
        "CO2bio": -0.368,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Biowaste {CH}| treatment of biowaste, industrial composting | Cut-off, S",
            "Biowaste {CH}| treatment of biowaste by anaerobic digestion | Cut-off, S",
            "Biowaste {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
        ],
    },
    "glass wool": {  # Ecoinvent
        "name": "Glass wool mat {CH}| production | Cut-off, S",
        "lambda": 0.036,
        "density": 22,
        "CO2bio": -0,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Waste mineral wool {Europe without Switzerland}| market for waste mineral wool | Cut-off, S",
            "Waste mineral wool, for final disposal {Europe without Switzerland}| market for waste mineral wool, final disposal | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, collection for final disposal | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, recycling | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, sorting plant | Cut-off, S",
            "Waste mineral wool, for final disposal {CH}| treatment of waste mineral wool, inert material landfill | Cut-off, S",
            "Waste mineral wool, for final disposal {Europe without Switzerland}| treatment of waste mineral wool, inert material landfill | Cut - off, S",
        ],
    },
    "stone wool": {  # Ecoinvent
        "name": "Stone wool {CH}| stone wool production | Cut-off, S",
        "lambda": 0.036,
        "density": 29.5,
        "CO2bio": -0,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Waste mineral wool {Europe without Switzerland}| market for waste mineral wool | Cut-off, S",
            "Waste mineral wool, for final disposal {Europe without Switzerland}| market for waste mineral wool, final disposal | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, collection for final disposal | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, recycling | Cut-off, S",
            "Waste mineral wool {Europe without Switzerland}| treatment of waste mineral wool, sorting plant | Cut-off, S",
            "Waste mineral wool, for final disposal {CH}| treatment of waste mineral wool, inert material landfill | Cut-off, S",
            "Waste mineral wool, for final disposal {Europe without Switzerland}| treatment of waste mineral wool, inert material landfill | Cut - off, S",
        ],
    },
    "XPS": {  # Ecoinvent
        "name": "Polystyrene, extruded {RER}| polystyrene production, extruded, CO2 blown | Cut-off, S",
        "lambda": 0.033,
        "density": 40,  # placeholder
        "CO2bio": -0,
        "rotation": 1,
        "lifetime": 50,
        "waste": [
            "Waste polystyrene {GLO}| market for | Cut-off, S",
            "Waste expanded polystyrene {GLO}| market for | Cut-off, S",
            "Waste polystyrene {CH}| market for waste polystyrene | Cut-off, S",
            "Waste polystyrene {Europe without Switzerland}| market for waste polystyrene | Cut-off, S",
            "Waste polystyrene {RoW}| market for waste polystyrene | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {CH}| market for waste polystyrene isolation, flame-retardant | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {Europe without Switzerland}| market for waste polystyrene isolation, flame-retardant | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {RoW}| market for waste polystyrene isolation, flame-retardant | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {CH}| treatment of, collection for final disposal | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {Europe without Switzerland}| treatment of waste polystyrene isolation, flame-retardant, collection for final disposal | Cut-off, S",
            "Waste polystyrene isolation, flame-retardant {RoW}| treatment of, collection for final disposal | Cut-off, S",
            "Waste expanded polystyrene {CH}| treatment of, municipal incineration | Cut-off, S",
            "Waste expanded polystyrene {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
            "Waste expanded polystyrene {RoW}| treatment of, municipal incineration | Cut-off, S",
            "Waste polystyrene {CH}| treatment of, municipal incineration | Cut-off, S",
            "Waste polystyrene {CH}| treatment of, municipal incineration with fly ash extraction | Cut-off, S",
            "Waste polystyrene {Europe without Switzerland}| treatment of waste polystyrene, municipal incineration | Cut-off, S",
            "Waste polystyrene {RoW}| treatment of waste polystyrene, municipal incineration | Cut-off, S",
            "Waste polystyrene {CH}| treatment of, sanitary landfill | Cut-off, S",
            "Waste polystyrene {Europe without Switzerland}| treatment of waste polystyrene, sanitary landfill | Cut-off, S",
            "Waste polystyrene {RoW}| treatment of waste polystyrene, sanitary landfill | Cut-off, S",
        ],
    },
}
#+end_src

*** Module B

Model module B - replacement after functional lifetime.
  - In a dynamic model, module B should also be dynamic. I.e. start a whole new
    product lifecycle.
  - Can only be done after adding modules C & D

I can use copies of the dataset but only when I first have a dataset which for
each house models:
- construction
- waste spike after product lifetime
for each replacement.

Then at the end-of-life for the building add 1 more waste spike.

Example showing Edge case if building_lt % product_lt == 0:
- e.g. ceil(75 / 50) - 1 = 2  - 1 = 1 -> 1 replacement
- e.g. ceil(100 / 25) - 1 = 4 - 1 = 3 ->  3 replacements
- A replacement includes both module A and module C/D costs
- After building lifetime add EoL cost (only module C/D)

** TODO

- Look into rounding off of numbers when reading in dataset
  - happens in .astype(float)
- Remove placeholder values
  - M2 Facades, Rvalue, lambda values

* Demo

housing scenarios
#+begin_src python
houses_per_year_slow(150000, 27)
houses_per_year_fast(150000, 27)
#+end_src

Large differences between cork / cellulose / stone wool
Francesco: cork is an 'anomaly' in the EcoInvent dataset, high production energy.
#+begin_src python
dataset = make_datasets()
dataset['cork']
dataset['stone wool']
dataset['cellulose']
#+end_src

Plotting them:
#+begin_src python
plot_GWI(['cork', 'cellulose', 'stone wool'], building_scenario='normal', plottype='inst')
plot_GWI(['cork', 'cellulose', 'stone wool'], building_scenario='normal', plottype='cum')
#+end_src
